# Generated by Django 5.1.7 on 2025-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Usertype',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
